[SETTINGS]
# Ruta donde se guardarán las canciones
output_dir = ~/Music

# Calidad de audio: 320, 192, 128
quality = 320

# Formato: mp3, m4a, ogg, wav
format = mp3

# Sincronización MPD: true o false
auto_update_mpd = true
